apiVersion: v1
kind: Service
metadata:
  name: corekube-worker
spec:
  ports:
  - name: worker-s1ap
    port: 5566
    targetPort: 5566
    protocol: UDP
  selector:
    app: corekube-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corekube-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corekube-worker
  template:
    metadata:
      labels:
        app: corekube-worker
    spec:
      containers:
      - name: corekube-worker
        image: corekube-worker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5566
          protocol: UDP
          name: worker-s1ap
        command: ["./corekube_udp_worker", "$(THIS_POD_IP)", "$(COREKUBE_DB_SERVICE_HOST)"]
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: corekube-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corekube-worker
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5


---


apiVersion: v1
kind: Service
metadata:
  name: corekube-db
spec:
  ports:
  - port: 7788
    targetPort: 7788
    protocol: TCP
  selector:
    app: corekube-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corekube-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corekube-db
  template:
    metadata:
      labels:
        app: corekube-db
    spec:
      containers:
      - name: corekube-db
        image: corekube-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7788
          protocol: TCP
        command: ["./corekubeDB"]


---


apiVersion: v1
kind: Service
metadata:
  name: corekube-frontend
spec:
  ports:
  - port: 36412
    targetPort: 36412
    protocol: SCTP
  selector:
    app: corekube-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: corekube-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corekube-frontend
  template:
    metadata:
      labels:
        app: corekube-frontend
    spec:
      containers:
      - name: corekube-frontend
        image: corekube-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 36412
          protocol: STCP
        command: ["./corekube_udp_frontend", "$(THIS_POD_IP)", "$(COREKUBE_WORKER_SERVICE_HOST)"]
        env:
        - name: THIS_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
